name: dynamic_tabs
description: A Flutter plugin for letting the user edit the bottom tabs like the
  Cupertino iTunes App.
version: 1.1.1-nullsafety
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/plugins
issue_tracker: https://github.com/rodydavis/dynamic_tabs

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_controllers: ^1.0.2-nullsafety
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
